<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Eit-Track" duration-ms="26199" started-at="2019-12-18T04:40:55Z" finished-at="2019-12-18T04:41:21Z">
    <groups>
    </groups>
    <test name="Login_TestCase" duration-ms="26199" started-at="2019-12-18T04:40:55Z" finished-at="2019-12-18T04:41:21Z">
      <class name="com.eit.stepdefinition.Login_page_test_case">
        <test-method status="PASS" signature="browse(java.lang.String)[pri:0, instance:com.eit.stepdefinition.Login_page_test_case@464bee09]" name="browse" is-config="true" duration-ms="6669" started-at="2019-12-18T10:10:55Z" finished-at="2019-12-18T10:11:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://spqa.thegoldenelement.com/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browse -->
        <test-method status="FAIL" signature="English_and_Arabic_Login_with_incorrect_Corporate_ID_or_User_name(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.eit.stepdefinition.Login_page_test_case@464bee09]" name="English_and_Arabic_Login_with_incorrect_Corporate_ID_or_User_name" duration-ms="4458" started-at="2019-12-18T10:11:02Z" finished-at="2019-12-18T10:11:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[AAAA]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo-ca]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[English_Login_with_incorrect_Corporate_ID_or_User_name = Expected Result:Enter Correct CorporateID or User name but it shows ->Enter Valid Corporate Id expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: English_Login_with_incorrect_Corporate_ID_or_User_name = Expected Result:Enter Correct CorporateID or User name but it shows ->Enter Valid Corporate Id expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.eit.stepdefinition.Login_page_test_case.English_and_Arabic_Login_with_incorrect_Corporate_ID_or_User_name(Login_page_test_case.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- English_and_Arabic_Login_with_incorrect_Corporate_ID_or_User_name -->
        <test-method status="PASS" signature="closee()[pri:0, instance:com.eit.stepdefinition.Login_page_test_case@464bee09]" name="closee" is-config="true" duration-ms="686" started-at="2019-12-18T10:11:07Z" finished-at="2019-12-18T10:11:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closee -->
        <test-method status="PASS" signature="browse(java.lang.String)[pri:0, instance:com.eit.stepdefinition.Login_page_test_case@464bee09]" name="browse" is-config="true" duration-ms="10335" started-at="2019-12-18T10:11:07Z" finished-at="2019-12-18T10:11:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://spqa.thegoldenelement.com/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browse -->
        <test-method status="FAIL" signature="English_and_Arabic_Login_with_incorrect_Corporate_ID_or_User_name(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.eit.stepdefinition.Login_page_test_case@464bee09]" name="English_and_Arabic_Login_with_incorrect_Corporate_ID_or_User_name" duration-ms="2362" started-at="2019-12-18T10:11:18Z" finished-at="2019-12-18T10:11:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[AAAA]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo-ca]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[English_Login_with_incorrect_Corporate_ID_or_User_name = Expected Result:Enter Correct CorporateID or User name but it shows ->Upgrading to newer version. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: English_Login_with_incorrect_Corporate_ID_or_User_name = Expected Result:Enter Correct CorporateID or User name but it shows ->Upgrading to newer version. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.eit.stepdefinition.Login_page_test_case.English_and_Arabic_Login_with_incorrect_Corporate_ID_or_User_name(Login_page_test_case.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- English_and_Arabic_Login_with_incorrect_Corporate_ID_or_User_name -->
        <test-method status="PASS" signature="closee()[pri:0, instance:com.eit.stepdefinition.Login_page_test_case@464bee09]" name="closee" is-config="true" duration-ms="696" started-at="2019-12-18T10:11:21Z" finished-at="2019-12-18T10:11:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closee -->
      </class> <!-- com.eit.stepdefinition.Login_page_test_case -->
    </test> <!-- Login_TestCase -->
  </suite> <!-- Eit-Track -->
</testng-results>
